name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - 
        name: Setup .npmrc
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@premisedata'
      - 
        name: Install dependencies
        run: npx oao bootstrap --production
      - 
        name: Build TypeScript
        run: yarn tsc
      - 
        name: Build packages
        run: npx oao run-script build --parallel
      - 
        name: Publish package to GitHub Packages
        run: npx oao publish --no-confirm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
