name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v5.0.2
        id: semantic
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          bump_each_commit: true
          # change_path: "packages/"
      - 
        run: |
          echo 'Debug output: ${{ toJSON(steps.semantic.outputs) }}'
      # Setup .npmrc file to publish to GitHub Packages
      - 
        name: Setup .npmrc
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@premisedata'
      - 
        name: Install dependencies
        run: npx oao bootstrap --production
      - 
        name: Build TypeScript
        run: yarn tsc
      - 
        name: Build packages
        run: npx oao run-script build --parallel
      - 
        # if: steps.semantic.outputs.changed == true
        name: Publish package to GitHub Packages
        run: npx oao publish --no-confirm --increment-version-by ${{ steps.semantic.outputs.version_type }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
